server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true

spring:
  application:
    name: Precision Tax Calculation System
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 10
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json